create table if not exists public.siigo_sync_runs (
    id bigint generated by default as identity primary key,
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    status text not null check (status in ('running', 'completed', 'failed')),
    sync_mode text not null,
    from_date date not null,
    to_date date not null,
    invoices_fetched integer not null default 0,
    customers_upserted integer not null default 0,
    sellers_upserted integer not null default 0,
    invoices_upserted integer not null default 0,
    error_message text,
    metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.siigo_customers (
    customer_id text primary key,
    identification text,
    branch_office text not null default '0',
    customer_name text not null,
    commercial_name text,
    person_type text,
    active boolean not null default true,
    vat_responsible boolean not null default false,
    email text,
    phone text,
    address_line text,
    city_name text,
    state_name text,
    country_name text,
    source_payload jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

create table if not exists public.siigo_sellers (
    seller_id text primary key,
    seller_name text not null,
    username text,
    email text,
    identification text,
    active boolean not null default true,
    source_payload jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

create table if not exists public.siigo_invoices (
    invoice_id text primary key,
    document_id text,
    invoice_name text,
    prefix text,
    number text,
    invoice_date date not null,
    invoice_month date,
    customer_id text references public.siigo_customers(customer_id),
    customer_identification text,
    customer_branch_office text,
    customer_name text,
    seller_id text references public.siigo_sellers(seller_id),
    seller_name text,
    seller_identification text,
    seller_email text,
    total_amount numeric(18, 2) not null default 0,
    paid_amount numeric(18, 2) not null default 0,
    balance_amount numeric(18, 2) not null default 0,
    annulled boolean not null default false,
    currency_code text,
    source_created_at timestamptz,
    sync_run_id bigint references public.siigo_sync_runs(id),
    raw_payload jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

create index if not exists idx_siigo_invoices_invoice_date
    on public.siigo_invoices (invoice_date);

create index if not exists idx_siigo_invoices_invoice_month
    on public.siigo_invoices (invoice_month);

create index if not exists idx_siigo_invoices_customer_id
    on public.siigo_invoices (customer_id);

create index if not exists idx_siigo_invoices_seller_id
    on public.siigo_invoices (seller_id);

create index if not exists idx_siigo_invoices_annulled
    on public.siigo_invoices (annulled);

create index if not exists idx_siigo_sync_runs_status
    on public.siigo_sync_runs (status, started_at desc);

-- Recibos de caja (v1/vouchers) — fuente de fechas reales de cobro
create table if not exists public.siigo_vouchers (
    voucher_id          text primary key,
    voucher_name        text,
    voucher_number      text,
    voucher_date        date not null,
    voucher_month       date,
    customer_id         text references public.siigo_customers(customer_id),
    customer_identification text,
    voucher_type        text,
    source_created_at   timestamptz,
    sync_run_id         bigint references public.siigo_sync_runs(id),
    raw_payload         jsonb not null default '{}'::jsonb,
    updated_at          timestamptz not null default now()
);

-- Líneas del recibo: cada factura que se canceló en ese recibo
create table if not exists public.siigo_voucher_items (
    id              bigint generated by default as identity primary key,
    voucher_id      text references public.siigo_vouchers(voucher_id) on delete cascade,
    voucher_date    date not null,
    voucher_month   date,
    invoice_name    text,       -- ej. FV-1-1421 → une con siigo_invoices.invoice_name
    invoice_prefix  text,
    invoice_number  integer,
    value           numeric(18, 2) not null default 0,
    updated_at      timestamptz not null default now()
);

create index if not exists idx_siigo_vouchers_voucher_date
    on public.siigo_vouchers (voucher_date);

create index if not exists idx_siigo_vouchers_voucher_month
    on public.siigo_vouchers (voucher_month);

create index if not exists idx_siigo_voucher_items_voucher_id
    on public.siigo_voucher_items (voucher_id);

create index if not exists idx_siigo_voucher_items_invoice_name
    on public.siigo_voucher_items (invoice_name);

create index if not exists idx_siigo_voucher_items_voucher_month
    on public.siigo_voucher_items (voucher_month);
